### PR TITLE
[WIP] [flat] N64 Overlay: Independent C-Button support

### PR DESCRIPTION
**Pull request by DewOnTheGrass**
Added set of overlay pages to properly address the ParaLLEl "Independent C-Button" option, and added a button to switch between the two overlay groups.

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
Hi, good work :) Does this affect the loading speed at all? If so, we might want to break it off to its own overlay.

**Comment by DewOnTheGrass** [comment]
Oh dear. I just tested it. Everything's screwy. To the drawing board again. I'll be back.

**Comment by DewOnTheGrass** [comment]
Okay, so all my button inputs match up properly to those specified in the ParaLLEl core under alternate input, but they act as if I had pressed the specified inputs on a normal controller, e.g. c-left has the function of the left trigger and c-down has the function of A, instead of both acting as, well, c-buttons.

Am I misunderstanding the effects of independent c-button mode?

**Comment by hizzlekizzle** [comment]
Hmm, that's a good question. The overlays act strangely sometimes insofar as I don't think they're affected by the input remapping(?), so maybe they sidestep the independent c-button mode, too?

But I guess that can't be right because you said the independent c-button option screwed up the normal overlay for you, right?

**Comment by DewOnTheGrass** [comment]
Yep. I would presume so. :/
However (!), after a good deal of testing, I think I may have solved it. I'll get back to you after dinner.

**Comment by DewOnTheGrass** [comment]
Alright. I figured out what I did wrong, and I made a new overlay with the n64.cfg from gamepads/n64 .
I have yet to re-revamp gamepads/flat/nintendo64.cfg, although that is my next step. I'll open up the other pull request, and mark this one WIP until I get around to it, I suppose.

**Comment by hizzlekizzle** [comment]
Looks good with the regular overlay. You're still working on the flat version?

**Comment by DewOnTheGrass** [comment]
I'm going to close this pull request and try this again; I don't fully understand GitHub.

**Pull request closed without merging**
