### PR TITLE
Add nice borders from LodanZark

### PR DESCRIPTION
**Pull request by gizmo98**
http://blog.petrockblock.com/forums/topic/mega-drivergenesis-side-pillar
boxs-psd/
http://blog.petrockblock.com/forums/topic/gba-overlay-psd/
http://blog.petrockblock.com/forums/topic/gameboy-overlay-settings-psd/

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
These are indeed very nice but I worry about the size. We have to keep it as low as possible for people downloading over their mobile connections from the online updater.

**Comment by gizmo98** [comment]
Do you have any idea to shrink size? I can remove some gameboy borders for example. It would  be a shame to withhold them.

**Comment by hizzlekizzle** [comment]
I try to stick to a few hundred kilobytes per image, tops, which pretty much rules out TV photos, etc. There's also the concern for the gameboy/gba borders that they require some pretty specific custom viewport options that there's not really any way to communicate to users.

**Comment by gizmo98** [comment]
Sounds good. It would be nice if there is some room left for vectrex overlays as well:
http://blog.recalbox.com/forums/topic/vectrex/page/5/

**Comment by wyatt8740** [comment]
I'd also suggest using a tool like "pngcrush" (NOT Apple's version) to shrink the images just a wee bit more.

**Comment by twinaphex** [comment]
What's the status on this now? Should we merge this or not?

**Comment by hizzlekizzle** [comment]
I think we should close it. It would add a lot of size to the overlays and a number of them require special viewport options that there's no way to communicate to users.

**Pull request closed without merging**
