### PR TITLE
small/big face buttons (A and B overlays), hide/show option, osk_toggle

### PR DESCRIPTION
**Pull request by sergiobenrocha2**
retropad_b

Also added a retropad fast overlay, the full featured one takes almost 4 seconds or more to load...

### CODE REVIEW

**Comment by sergiobenrocha2** [comment]
Btw, is it hard to get this set as the default in android? :) 

The retropad overlays has almost all things needed now

**Comment by hizzlekizzle** [comment]
shouldn't be hard to change defaults. I think it's just an entry in a config somewhere. we can ask radius where to find it.

**Comment by sergiobenrocha2** [comment]
I mean, is this better than the default now?

**Comment by hizzlekizzle** [comment]
I haven't used it to see if it controls better, but it looks nicer, I think, and they seem better-designed (e.g., the extra L1 by the buttons)

**Comment by sergiobenrocha2** [comment]
They should be used with Overrides Files ON. I'll try to make for every console.

**Comment by fr500** [comment]
Did you change the original flat overlay? that one had some offset between the buttons and the actual touch zones that made it great.

Does your overlay have that too?

**Comment by sergiobenrocha2** [comment]
Are you speaking about this?

flat-base - 1136x640

I kinda didn't like, and the d-pad touch zones are too small

**Comment by sergiobenrocha2** [comment]
The touch zone surpass something like 3 to 6 pixels of the picture, for d-pad is more, 9~11

retropad-b - 960x540 - green marks

**Comment by fr500** [comment]
you are not answering my question, I asked if you modified the original one
not for an explanation

**Comment by hizzlekizzle** [comment]
For context, the guy who made the original one made a little program that registered touch locations and then he drew the overlay on the screen and had people touch the overlay buttons, then he based the hitboxes on that data. Interestingly, the hitboxes were not lined up with the overlay images, presumably because the places where people put their thumbs register differently from where they're expecting.

**Comment by fr500** [comment]
yeah I remember he studied the thing and it does work better than just
"bigger" overlays so I'd like to keep that one as it was

**Comment by sergiobenrocha2** [comment]
I barely based in the old one, I got only the idea of the shoulder buttons.

**Pull request merged**
