### PR TITLE
Add 'neo-retropad' gamepad overlays

### PR DESCRIPTION
**Pull request by jdgleaver**
This PR adds a new 'neo-retropad' gamepad overlay. This is a general purpose 'set and forget' controller with the following design goals:

- Directional inputs + face buttons should be in ergonomic locations

- Overlay elements should cover as little of the active (gameplay) viewport as possible

Two variants are provided - here are some screenshots, all taken with a display aspect ratio of 16:9 (or 16:9 rotated):

## `neo-retropad.cfg`

Screenshot_2020-09-11_14-43-08

Screenshot_2020-09-11_14-43-50

Screenshot_2020-09-11_14-47-07

Screenshot_2020-09-11_14-49-50

Screenshot_2020-09-11_14-49-58

Screenshot_2020-09-11_14-51-56

## `neo-retropad-clear.cfg`

Screenshot_2020-09-11_14-45-56

Screenshot_2020-09-11_14-47-43

Screenshot_2020-09-11_14-50-15

Screenshot_2020-09-11_14-50-24

Screenshot_2020-09-11_14-52-26

------

When using 18:9 aspect ratio phones, the `Overlay Horizontal Separation` factor can be set such that even GBA content can be played in landscape mode with minimal infringement on the game viewport.

All source files (including layout mock-ups and a trivial helper script) are included, which may serve as a helpful reference for others who want to make gamepad overlays (it's a great deal fiddlier than one might imagine...).

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
Looks great to me. Is there any reason we shouldn't make it the new default in RetroArch, once it's merged?

**Comment by jdgleaver** [comment]
Thanks!

I was indeed thinking of making this the new default (might improve our image among Android users, at least). I was just waiting to see if anyone had any comments/complaints.

I can certainly PR the code change on the RA side - that's no trouble at all :)

**Comment by hizzlekizzle** [comment]
May as well make it default for now and if we get complaints, we can always fall back. :)

**Comment by jdgleaver** [comment]
Okay, sounds good :)

**Pull request merged**
